# file: .github/workflows/show-directory.yml
name: show-directory
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
           node-version: '18'
      # run – произвольная bash-команда
      # ls -la выведет содержимое текущего репозитория
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Hello from Hexlet
        uses: hexlet-components/hello-from-hexlet-action@v1







